---
title: "Lauren's sandpit"
output: html_notebook
---

This notebook is just somewhere for Lauren to try stuff out.

```{r setup, include = FALSE}
library(tidyverse)
library(lubridate)
articles <- read_csv("data/master.csv")
```

looking at number of news mentions over time. First need to join mentions and articles_since_publication. Next group by DOI.

```{r news mentions with time}
article_mentions_since_publication <- left_join(articles_since_publication, mentions)

summarise(
  group_by(filter(article_mentions_since_publication, source == "news"), 
           article_title),)

news_mentions_since_publication <- mutate(
  filter(group_by(filter(article_mentions_since_publication, source == "news"),
                  doi),
                  print_publication_date > "2013-01-01"), 
  days_since_publication = ymd("2018-07-13")-as_date(print_publication_date) 
)

news_mentions_aggregated <- summarise(
  group_by(news_mentions_since_publication, doi, days_since_publication),
  total = n()
)

ggplot(data = news_mentions_aggregated) +
  geom_point(mapping = aes(x = days_since_publication, y = total))



```
